### ISSUE TITLE
Broken Application API links in Identity.

### ISSUE THREAD

**Issue by gig-e** [cmu-sei/crucible#45]
The links to the API of the individual applications. 
Each link currently goes to <application_name>-api.domain_name.com when it should go to <application_name>-api.comain_name.com/api
For example in my case:
caster-api.cyvantage.io when it should be caster-api.cyvantage.io/api.

Identity & Identity UI version 1.28.

**Comment by sei-ebram** [comment]
Hi @gig-e,
Is this a bug in the appliance configuration?

**Comment by gig-e** [comment]
Hi @sei-ebram,
I'm not sure, I only have experience with the appliance. I upgraded to v0.0.5 last week, but noticed the same issue in earlier versions.

**Comment by sei-ebram** [comment]
@gig-e Thanks!  I tagged @sei-noconnor to look at this

**Comment by sei-noconnor** [comment]
The new URL's should be https://app.<domain>/api (https://caster.crucible.io/api) I'll need to look at the traefik configs and the identity configs and update.
