### ISSUE TITLE
Player Map Template

### ISSUE THREAD

**Issue by gig-e** [cmu-sei/crucible#46]
I'd like to create maps in player. I do not have the map template available to me in player. Any advice on how to add it manually?
I'm running the Crucible 3.0 Appliance, which include version 3.0 of player-ui, player-api, vm-api, vm-ui.

**Comment by sei-aschlackman** [comment]
The Map builder is part of the Vm Application, so you can create a new Application Template and use the same url as the in your Vm template, but with /map at the end (before {theme} if you have that in there, though I don't think the map builder supports the dark theme yet). So it should look like:

https://{your-vm-application-url}/views/{viewId}/map{theme}

**Comment by gig-e** [comment]
That worked perfectly, thanks!
