### ISSUE TITLE
Deploy directly from Rancher (Request)

### ISSUE THREAD

**Issue by usshauler** [cmu-sei/crucible#70]
Is there a way to deploy the entire solution from Rancher directly ? I would like to stand up the entire Crucible Framework instance using Rancher if possible, thank you.

**Comment by fkan2500** [comment]
hey unrelated to you issue were you able to install everything? I have having issues installing it and would like some assistance from anyone if that's possible. my email is farrukh.khan@jjay.cuny.edu

**Comment by sei-aschlackman** [comment]
@usshauler Hi, thanks for your interest in the project. Unfortunately we aren't using Rancher internally, and I haven't tried using it to deploy Crucible. We do, however, have helm charts and a helm repo for all of the apps that you may be able to use from Rancher here: https://github.com/cmu-sei/helm-charts. 

@fkan2500 Please open a new issue or discussion with details of the specific issues you are running into and I'll be happy to help as best as I can.
